### PR TITLE
WIP: Refactored the pull request

### PR DESCRIPTION
**Pull request by adelton**
* We store the password immediatelly after `auth` passes, no need to wait for `account`.
* Using random salt and bcrypt.
* Made compilation conditional so that it does not fail on 2.2.

### CODE REVIEW

**Comment by adelton** [comment]
Hmm, I'm getting Segmentation fault with my code. Will need to investigate some more.

**Comment by adelton** [comment]
Fixed -> acbc257a204d8bc083c758d4ef296d3e1eb96d0f.

**Comment by adelton** [comment]
I've added tests in CI to verify that the credential gets cached and that it timeouts properly.

If you are OK with https://github.com/schnitzi99/mod_authnz_pam/pull/1/commits/88b9598e1365cfe69f461c876b84ba31c00db782 as modification to your commit, I'll squash them and merge the changes.

Do you want to keep `schnitzi99 <41208145+schnitzi99@users.noreply.github.com>` as the authorship of your change, or would you prefer some more real name + email address?

**Comment by schnitzi99** [comment]
Did you solve the segmentation fault issue? I had a similar issue, because the length of the salt was wrong.

Modifications "88b9598" look fine to me, but keep in mind that I have rather basic programming knowledge (which is equivalent to "can only read and copy code") and I don't have any experience with github / git. Feel free to merge and squash and stuff. :)
If you need me to do anything to get things merged feel free to tell me.

Authorship "schnitzi99" is fine, but I'm fine with you taking authorship as well as you might be able to handle questions/comments way better than me. I'm happy that you are adapting / correcting stuff and make proper code of it. :)

**Comment by adelton** [comment]
> Did you solve the segmentation fault issue?

Yes -- in the first take I was running the code even for authorization code path where `password` was `NULL`.

**Comment by adelton** [comment]
Squashed, rebased, pushed to master as 9236628dbac1c2d99d752731e8391fa1307f2b0c.

**Pull request closed without merging**
